#!/bin/bash

# ========================================
# Manual Deployment Commands for Plesk
# Run these commands step by step in your SSH session
# ========================================

echo "======================================"
echo "📋 DEPLOYMENT COMMANDS FOR PLESK"
echo "======================================"
echo ""
echo "🔐 Step 1: SSH Login"
echo "------------------------------------"
echo "ssh okefor@139.99.114.128"
echo "Password: Boonyanone@5561"
echo ""
echo "------------------------------------"
echo "📥 Step 2: Navigate and Clone Repository"
echo "------------------------------------"
echo "cd play.okeforyou.com"
echo ""
echo "# Remove old files if directory not empty"
echo "rm -rf * .[^.] .??*"
echo ""
echo "# Clone from GitHub"
echo "git clone -b main https://github.com/okeforyou/youoke.git ."
echo ""
echo "------------------------------------"
echo "📦 Step 3: Install Dependencies"
echo "------------------------------------"
echo "npm install --production --legacy-peer-deps"
echo ""
echo "------------------------------------"
echo "🔨 Step 4: Build Next.js"
echo "------------------------------------"
echo "npm run build"
echo ""
echo "------------------------------------"
echo "🚀 Step 5: Setup PM2"
echo "------------------------------------"
echo "# Install PM2 globally if not installed"
echo "npm install -g pm2"
echo ""
echo "# Stop old process if exists"
echo "pm2 delete youoke-prod 2>/dev/null || true"
echo ""
echo "# Start application"
echo "pm2 start npm --name \"youoke-prod\" -- start"
echo ""
echo "# Save PM2 config"
echo "pm2 save"
echo ""
echo "# Setup auto-restart on reboot"
echo "pm2 startup"
echo ""
echo "------------------------------------"
echo "✅ Step 6: Verify Deployment"
echo "------------------------------------"
echo "pm2 status"
echo "pm2 logs youoke-prod --lines 50"
echo ""
echo "======================================"
echo "🎉 DONE! Check https://play.okeforyou.com"
echo "======================================"
echo ""
echo "💡 Useful PM2 Commands:"
echo "  pm2 status              - Check app status"
echo "  pm2 logs youoke-prod    - View logs"
echo "  pm2 restart youoke-prod - Restart app"
echo "  pm2 stop youoke-prod    - Stop app"
echo ""
